/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cute_axolotl.glb --transform --types
Files: cute_axolotl.glb [3.18MB] > /Users/teeb/repos/crudvale/public/cute_axolotl-transformed.glb [252.43KB] (92%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Object_4: THREE.Mesh
        Object_12: THREE.Mesh
        Object_14: THREE.Mesh
    }
    materials: {
        skin: THREE.MeshStandardMaterial
        head_things: THREE.MeshStandardMaterial
        face_elements: THREE.MeshStandardMaterial
    }
    animations: GLTFAction[]
}

export function Axolotl2(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(
        '/cute_axolotl-transformed.glb',
    ) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Object_4.geometry}
                material={materials.skin}
            />
            <mesh
                geometry={nodes.Object_12.geometry}
                material={materials.head_things}
                position={[0.296, -0.201, 1.142]}
                rotation={[-2.338, -0.131, 0.087]}
                scale={[-0.273, 0.273, 0.273]}
            />
            <mesh
                geometry={nodes.Object_14.geometry}
                material={materials.face_elements}
                position={[0.778, 0.14, 0.556]}
                rotation={[0.075, -0.293, 0.111]}
                scale={[0.091, 0.151, 0.151]}
            />
        </group>
    )
}

useGLTF.preload('/cute_axolotl-transformed.glb')
