# fly.toml app configuration file generated for wildernest on 2025-08-04T14:38:52-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wildernest'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
