/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --types bee1.glb
Files: bee1.glb [4.35MB] > /Users/teeb/repos/crudvale/public/bee1-transformed.glb [289.49KB] (93%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        model: THREE.Mesh
    }
    materials: {
        CustomMaterial: THREE.MeshStandardMaterial
    }
    animations: GLTFAction[]
}

export function Bee(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF<GLTFResult>(
        '/bee1-transformed.glb'
    ) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.model.geometry}
                material={materials.CustomMaterial}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

useGLTF.preload('/bee1-transformed.glb')
