# fly.toml app configuration file generated for db-wildernest on 2025-08-04T13:46:42-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'db-wildernest'
primary_region = 'yyz'

[build]
  image = 'mysql:8.0.37'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password  --performance-schema=OFF --innodb-buffer-pool-size 64M"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "app_db"
  MYSQL_USER = "app_user"