# fly.toml app configuration file generated for db-morning-wildflower-9602 on 2025-05-21T12:36:58-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'db-morning-wildflower-9602'
primary_region = 'yyz'

[build]
  image = 'mysql:8.0'



[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[processes]
app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
source = "mysqldata"
destination = "/data"

[env]
MYSQL_DATABASE = "wildernest_db"
MYSQL_USER = "wildernest_api"
