# fly.toml app configuration file generated for db-wildernest on 2025-08-17T12:39:12-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'db-wildernest'
primary_region = 'yyz'

[build]
  image = 'mysql:8.0.37'

[env]
  MYSQL_DATABASE = 'app_db'
  MYSQL_USER = 'api_user'

[processes]
  app = '--datadir /data/mysql --default-authentication-plugin mysql_native_password'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1